name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value:  Thank you for contributing to `pydantic-shapely`! âœŠ

  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: Just making sure you're really using Pydantic V2
      options:
        - label: I confirm that I'm using Pydantic V2
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. ðŸ™
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.

      placeholder: |
        from pydantic-shapely import GeometryField, FeatureBaseModel

        ...
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Python, Pydantic, Shapely & OS Version
      description: |
        Which version of Python, Pydantic & Shapely are you using, and which Operating System?

        Please run the following command and copy the output below:

        ```bash
        python -c "import shapely;import pydantic.version;import pydantic_shapely;print('Pydantic-shapely version:', pydantic_shapely.__version__);print('Shapely version:', shapely.__version__);print(pydantic.version.version_info())"
        ```

      render: Text
    validations:
      required: true
